Resources:
  ORInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - ORInstallation
        
        ORInstallation:
          commands:
            01_docker_installation:
              command: |
                yum install docker -y
                sudo usermod -a -G docker ec2-user
                systemctl start docker

            02_docker_compose_installation:
              command: |
                curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose
            
            03_download_docker_compose:
              command: |
                sudo wget https://raw.githubusercontent.com/FHICT-Dennis-Kuijs/openremote-aws-marketplace/864414845eeaf2b07973d7e69b623603f5eefb01/docker-compose.yml -P /openremote
            
            04_prepare_external_volume:
              command: !Sub |

                sudo mkdir -p /or-data

                sudo mkfs -t xfs /dev/sdb
                sudo mount /dev/sdb /or-data

                sudo mkdir -p /or-data/proxy
                sudo mkdir -p /or-data/postgres
                sudo mkdir -p /or-data/manager

                UUID=$(sudo blkid -s UUID -o value /dev/sdb)
                if [ -n "$UUID" ]; then
                   sudo cp /etc/fstab /etc/fstab.orig
                   echo "UUID=$UUID /or-data xfs defaults,nofail 0 2" | sudo tee -a /etc/fstab > /dev/null
                else
                  echo "Failed to create /etc/fstab entry. UUID is not found"
                fi
            
            05_start_openremote:
              command: !Sub |
                OR_HOSTNAME=$(curl v4.ident.me 2>/dev/null) OR_PROXY_DATA_PATH=/or-data/proxy OR_MANAGER_DATA_PATH=/or-data/manager OR_POSTGRES_DATA_PATH=/or-data/postgres docker-compose -f /openremote/docker-compose.yml -p openremote up -d
    
    Properties:
      ImageId: ami-0fc389ea796968582
      InstanceType: t4g.medium
      KeyName: OpenRemote
      SecurityGroupIds:
      -  sg-0029f6366cd749560
      Tags:
      - Key: Name
        Value: OpenRemote/AWS-Marketplace
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 30
          VolumeType: gp3
          DeleteOnTermination: true
      - DeviceName: /dev/sdb
        Ebs:
         VolumeSize: 1
         VolumeType: gp3
         DeleteOnTermination: false
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            yum -y install aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource ORInstance
  