# ---------------------------------------------------------------------------------------------------------------------
#
# CloudFormation Template for creating an Amazon Data Lifecycle Manager policy for creating snapshots of the EBS Data volume.
#
# ---------------------------------------------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an Lifecycle Policy for creating EBS snapshots'

Parameters:
  DLMExecutionRoleArn:
    Description: Role ARN for executing the DLM operations
    Type: String
  EBSStackId:
    Description: EBS Stack Id of the volume that need to be targeted by this policy
    Type: String

Resources:
  EBSPolicy:
    Type: AWS::DLM::LifecyclePolicy
    Properties:
      Description: Snapshot creation of EBS Volume
      ExecutionRoleArn: !Ref DLMExecutionRoleArn
      State: ENABLED
      PolicyDetails:
        PolicyLanguage: STANDARD
        PolicyType: EBS_SNAPSHOT_MANAGEMENT
        TargetTags:
          - Key: aws:cloudformation:stack-id
            Value: !Ref EBSStackId
        ResourceLocations:
          - CLOUD
        ResourceTypes: 
          - VOLUME
        Schedules:
          - Name: Daily Backup
            CreateRule:
              Interval: 24
              IntervalUnit: HOURS
              Times:
              - '05:00'
            RetainRule:
              Count: 5

